spring.application.name=matchup

spring.datasource.url=jdbc:mysql://localhost:3306/matchupdb
spring.datasource.username=root
spring.datasource.password=16102004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=druxxfmia
cloudinary.api_key=437992527572232
cloudinary.api_secret=ol1B4gKE-e_U-hqnpxnmPhD9nSA
